- hosts: dockerhost
  gather_facts: false
  tasks:
  - name: Creating Docker Repository
    yum_repository:
      name: docker
      description: Docker Repo
      file: /etc/yum.repos.d/docker
      baseurl: https://download.docker.com/linux/centos/7/x86_64/stable    
      gpgcheck: no
      enabled: true

  - name: Docker Package Installation
    command: "yum install docker-ce --nobest -y"

  - name: Install Software Python36
    package:
      name: "python36"
      state: present

  - name: Install Docker Python Library
    pip:
      name: "docker-py"

  - name: Starting Docker Service
    service:
      name: "docker"
      state: started

  - name: pull an image
    docker_image:
      name: ubuntu:14.04
      source: pull

  - name: Creating Docker Container
    docker_container:
      name: mywebserveros
      image: ubuntu:14.04
      state: started
      detach: true
      interactive: true    
