- hosts: testos
  
  vars:
  - pname: "httpd"
  - sname: "firewalld"  
  - body: "HOME PAGE"    
  
  tasks:
  - package:
     name: "{{  pname }}"
     state: "present"

  - copy:
     src: "index.html" 
     dest: "/var/www/html/index.html"
    ignore_errors: "yes"
    register: x 

  - service:
     name: "{{ pname }}"
     state: "started"

  - service:
     name: "{{ sname }}"
     state: "started"

  - debug:
     msg:  "TESTOS CONFIGURED"

- hosts: prodos
  
  vars:
  - pname: "httpd"
  - sname: "firewalld"  
  - body: "HOME PAGE"

  tasks:
  - package:
     name:  "{{ pname }}"
     state: "present"

  - copy:
     content: "{{ body }}"
     dest: "/var/www/html/index.html"
    ignore_errors: "yes"
    register: x 

  - service:
     name: "{{ pname }}"
     state: "started"

  - service:
     name: "{{ sname }}"
     state: "started"
  
  - debug:
     msg:  "PRODOS CONFIGURED"

