- hosts: dockerhost
  gather_facts: false
  tasks:
  - name: Creating Docker Repository
    yum_repository:
      name: docker
      description: Docker Repo
      file: /etc/yum.repos.d/docker
      baseurl: https://download.docker.com/linux/centos/7/x86_64/stable    
      gpgcheck: no
      enabled: true

  - name: Docker Package Installation
    command: "yum install docker-ce --nobest -y"

  - name: Install Software Python36
    package:
      name: python36
      state: present

  - name: Install Docker Python Library
    pip:
      name: docker-py

  - name: Creating A WorkSpace on MN
    file:
      path: /root/AnsibleTask1WebWS
      state: directory

  - name: Copying Content Into Managed Node
    copy:
      src: "index.html"
      dest: "/root/AnsibleTask1WebWS/"
    ignore_errors: yes

  - name: Starting Docker Service
    service:
      name: docker
      state: started

  - name: pull an image
    docker_image:
      name: httpd
      source: pull

  - name: Creating Docker Container
    docker_container:
      name: mywebserveros
      image: httpd
      state: started
      detach: true
      interactive: true
      ports:
      - "1111:80"
      volumes:
      - /root/AnsibleTask1WebWS/:/usr/local/apache2/htdocs/    
